project:
  type: website
  output-dir: docs
  preview:
    port: 4209
  render:
    - "*.qmd"
    - "!_*"


exclude: ["*.rds","*.tex"]


website:
  title: "CCL Projects"
  repo-url: https://github.com/tegorman13/ccl
  site-url: "https://tegorman13.github.io/ccl"
  reader-mode: true
  page-navigation: false
  sidebar:
    style: "docked"
    border: false
    collapse-level: 2
    pinned: false
    target: _blank
    tools:
    - icon: github
      href: https://github.com/tegorman13/ccl
    contents:
      #- index.qmd
      #- text: "---"
      - text: "---"
      - section: "AI Group Decision Making"
        contents:
        - ai_gd.qmd
      - text: "---"
      - section: "Misc"
        contents:
        - tms.qmd
        - Samuel_Project.qmd
        - Driving.qmd

format:
  html:
    theme:
      - cosmo
      - Assets/Style/style.scss
    css: Assets/Style/calloutTG.css
    code-link: false
    code-summary: "Display code"
    html-math-method: mathjax
    citations-hover: true
    link-external-newwindow: true



execute:
  freeze: auto



bibliography: [assets/ccl_bib.bib]
csl: assets/apa.csl